# -*- coding: utf-8 -*-
"""신입생 현황 전처리.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1clwXIFtChqMKnbqLfMTmJxZMPUniLaZa
"""

import pandas as pd
import re

# 파일 경로
file_path = "신입생 충원 현황_학과별자료(2010~2024).csv"

# UTF-8-SIG 인코딩으로 CSV 파일 불러오기
df = pd.read_csv(file_path, encoding='utf-8-sig')

# 컬럼 공백 제거
df.columns = df.columns.str.strip()

# 주요 컬럼 이름 파악
department_col = [col for col in df.columns if '학과' in col or '전공' in col][0]
school_col = [col for col in df.columns if '학교' in col][0]

# (1) 학과명에서 7자리 숫자 코드 제거
df[department_col] = df[department_col].str.replace(r"\(\d{7}\)", "", regex=True).str.strip()

# (2) 학교명에서 "_제2 캠퍼스", "_제3 캠퍼스", "_분교" 등 제거
df[school_col] = df[school_col].str.replace(r"_제\d\s?캠퍼스", "", regex=True)
df[school_col] = df[school_col].str.replace(r"_분교", "", regex=True)
df[school_col] = df[school_col].str.strip()

# (3) 학교명에서 '국립'으로 시작하지만 '국립경국대학교'는 제외하고 '국립' 제거
mask = df[school_col].str.startswith('국립') & (df[school_col] != '국립경국대학교')
df.loc[mask, school_col] = df.loc[mask, school_col].str.replace('^국립', '', regex=True).str.strip()

# (4) 전처리된 데이터를 새로운 CSV 파일로 저장
output_path = "전처리된_신입생_충원_현황(2010~2024).csv"
df.to_csv(output_path, index=False, encoding='utf-8-sig')

print(f"파일이 저장되었습니다: {output_path}")

# 파일 불러오기
df_main = pd.read_csv("전처리된_신입생_충원_현황(2010~2024).csv", encoding="utf-8")
df_ref = pd.read_csv("학교별 교육편제단위 정보 정리본.csv", encoding="utf-8")

# 컬럼명 공백 제거
df_main.columns = df_main.columns.str.strip()
df_ref.columns = df_ref.columns.str.strip()

# 중복 제거: 학교명 + 학과명 조합으로 하나만 남기기
df_ref_unique = df_ref.drop_duplicates(subset=["학교명", "학과명"])

# 병합
merged = pd.merge(
    df_main,
    df_ref_unique[["학교명", "학과명", "대학자체대계열"]],
    left_on=["학교", "학과"],
    right_on=["학교명", "학과명"],
    how="left"
)

# 중복 컬럼 제거
merged.drop(columns=["학교명", "학과명"], inplace=True)

# 저장
merged.to_csv("신입생_충원현황_대계열추가.csv", index=False, encoding="utf-8-sig")