# -*- coding: utf-8 -*-
"""emply.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15E86Q4vk_sKhFvezyQ_FExtWoGP7Ceur
"""

# 데이터 불러오기
import pandas as pd

df_raw = pd.read_csv("employ.csv")

# 컬럼 설정
df_cl = df_raw.copy()
df_cl.columns = df_cl.iloc[0]

# 인덱스 재설정
df_cl = df_cl.reset_index(drop = True)

# 필요한 데이터만 남기기
df_cl = df_cl[4:]
df_cl = df_cl.iloc[:,:4]

# 컬럼명 변경
df_cl.columns = ['기준년도', '학교명', '졸업자', '취업률']

# 쉼표(,) 제거
df_cl['졸업자'] = df_cl['졸업자'].str.replace(',', '', regex=False)

# 비어있는 값에 이전 행 값 삽입
df_cl['기준년도'] = df_cl['기준년도'].fillna(method='ffill')

# 타입 변경
df_cl['기준년도'] = df_cl['기준년도'].astype(int)
df_cl['졸업자'] = df_cl['졸업자'].astype(int)
df_cl['취업률'] = df_cl['취업률'].astype(float)

# 데이터프레임을 csv 파일로 저장
df_cl.to_csv('cleaned_employ.csv', index = False, encoding = 'utf-8-sig')

df_cl.info()
df_cl.head()